language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8
  - openjdk9
branches:
  only:
    - master

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V